### ISSUE TITLE
网站密码如何找回？

### ISSUE THREAD

**Issue by itunic** [axumrs/axum-rs#1]
rt

**Comment by axumrs** [comment]
你好，暂时没有“自助”找回密码的功能。请发送邮件给我们，我们会将你的密码重置为随机密码，并通过邮件回复给你：

收件人：team@axum.rs
主题：重置密码
内容：（空）


注意：请使用你在 axum.rs 注册的邮箱地址发送以上邮件，我们重置密码的依据之一就是你发送这封邮件的邮箱地址。
